// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgoycqvcdrgbnieesnop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnb3ljcXZjZHJnYm5pZWVzbm9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczOTE4MDUsImV4cCI6MjA3Mjk2NzgwNX0.38SyWi49ftr0z7T9-jzJEaJN8en30lnj87_eb3M6z3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});